[tool.poetry]
name = "pybuc"
version = "0.16.3"
description = "Fast estimation of Bayesian structural time series models via Gibbs sampling."
authors = ["Devin D. Garcia"]
license = "BSD 3-Clause"
readme = "README.md"
keywords = ["structural", "time series", "unobserved components",
            "bayesian", "bsts", "forecast", "state space"]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
numba = "0.56.4"
pandas = "^2.0.1"
numpy = "1.23.5"
matplotlib = "^3.6.1"
twine = "^4.0.2"
scipy = "^1.10.1"
seaborn = "^0.12.2"

[tool.poetry.dev-dependencies]
statsmodels = "^0.14.0"

[tool.poetry.urls]
repository = "https://github.com/devindg/pybuc"
homepage = "https://github.com/devindg/pybuc"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
