[tool.poetry]
name = "pybuc"
version = "0.11.0"
description = "Fast estimation of Bayesian structural time series models via Gibbs sampling."
authors = ["Devin D. Garcia"]
license = "BSD 3-Clause"
readme = "README.md"
keywords = ["structural time series", "unobserved components", "bayesian", "bsts"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numba = "^0.56.2"
pandas = "^1.4.4"
numpy = "^1.23.2"
matplotlib = "3.5.2"

[tool.poetry.dev-dependencies]
statsmodels = "^0.13.2"

[tool.poetry.urls]
repository = "https://github.com/devindg/pybuc"
homepage = "https://github.com/devindg/pybuc"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
