[tool.poetry]
name = "pybuc"
version = "0.4.10"
description = "Fast estimation of Bayesian structural time series models via Gibbs sampling."
authors = ["Devin D. Garcia"]
license = "BSD 3-Clause"
readme = "README.md"
keywords = ["structural time series", "unobserved components", "bayesian", "bsts"]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
numba = "^0.56.0"
pandas = "^1.4.3"
matplotlib = "^3.5.3"
scipy = "^1.9.1"

[tool.poetry.dev-dependencies]
statsmodels = "^0.13.2"

[tool.poetry.urls]
repository = "https://github.com/devindg/pybuc"
homepage = "https://github.com/devindg/pybuc"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
